fix pathconf call on prefix instead of path
path is not defined, but we have prefix.

this fixes a build failure on systems which do not have PATH_MAX:

    /<<PKGBUILDDIR>>/src/unshield.c: In function 'extract_file':
    /<<PKGBUILDDIR>>/src/unshield.c:373:25: error: 'path' undeclared (first use in this function)
         path_max = pathconf(path, _PC_PATH_MAX);